# Generated by Django 4.1.3 on 2022-12-06 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFlia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiares',
            name='edad',
            field=models.IntegerField(),
        ),
    ]
