# Generated by Django 4.1.3 on 2022-12-06 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFlia', '0002_alter_familiares_edad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiares',
            name='rol',
        ),
    ]
